### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by Serpent27** [commandblockguy/tanks-ce#1]
I tried building from source, but I get syntax errors in `src/util.h`. Attempting to resolve these leads to more errors.

I understand this is only in alpha, but I very much like your work and was hoping I could play the latest version...

**Comment by Serpent27** [comment]
![20201104_011821.jpg](https://user-images.githubusercontent.com/66246604/98086205-579fd980-1e76-11eb-8500-12a82efdfda1.jpg)

**Comment by commandz0** [comment]
Tanks! builds using the LLVM branch of the toolchain, which is currently in pre-release stages. The LLVM branch adds support for newer C features, which I'm now using in this project.
You can download the latest LLVM branch build of the toolchain [here](https://github.com/CE-Programming/toolchain/actions?query=branch%3Allvm)
You'll also need ez80-clang, which you can download [here](https://github.com/jacobly0/llvm-project/actions)

I also just added a binary for the latest commit of Tanks! [here](https://github.com/commandblockguy/tanks-ce/releases/tag/v0.6-alpha), if you just want to download that instead.
